export const MISSIONS = [
  {
    id: 'ssh-brute-force',
    name: 'SSH Brute Force Defense',
    category: 'Incident Response',
    difficulty: 1,
    xp: 150,
    estimatedTime: '10 min',
    icon: '🔨',
    color: '#ff8800',
    briefing: `ALERT: Intrusion Detection System has flagged suspicious authentication activity on web-server-1 (192.168.1.11).\n\nOur IDS reports over 500 failed SSH login attempts from IP 185.220.101.47 in the past 15 minutes. The source IP is a known TOR exit node.\n\nYour mission: Investigate the attack, confirm the source, and block the attacker before they gain access.`,
    attackConfig: { type: 'bruteforce', targetId: 'web-server-1' },
    systemState: { bruteforce: true },
    objectives: [
      {
        id: 'check-logs',
        text: 'Investigate SSH authentication logs',
        hint: 'Try: journalctl -u ssh -n 30  or  cat /var/log/auth.log',
        pattern: /journalctl.*ssh|cat.*auth\.log|tail.*auth\.log|grep.*auth\.log/i,
        explanation: 'Authentication logs in /var/log/auth.log record all login attempts. journalctl -u ssh filters only SSH service events. Look for "Failed password" entries to identify attackers.',
        visualEffect: 'highlight_node:web-server-1',
        completed: false,
      },
      {
        id: 'identify-ip',
        text: 'Identify the attacker\'s IP address',
        hint: 'grep "Failed password" /var/log/auth.log | awk \'{print $11}\' | sort | uniq -c',
        pattern: /grep.*[Ff]ailed|grep.*185\.220|awk.*print.*11/i,
        explanation: 'Pattern analysis reveals 185.220.101.47 as the source. This IP belongs to a known TOR exit node used for anonymizing malicious activity.',
        visualEffect: 'pulse_node:external-attacker',
        completed: false,
      },
      {
        id: 'block-ip',
        text: 'Block the attacker IP with iptables or ufw',
        hint: 'iptables -A INPUT -s 185.220.101.47 -j DROP  OR  ufw deny from 185.220.101.47',
        pattern: /iptables.*185\.220\.101\.47|ufw.*deny.*185\.220|fail2ban.*banip.*185\.220/i,
        explanation: 'iptables -A INPUT -s <IP> -j DROP adds a rule to drop all packets from that source. UFW (Uncomplicated Firewall) provides a simpler interface to iptables rules.',
        visualEffect: 'firewall_shield:web-server-1',
        completed: false,
      },
      {
        id: 'verify-block',
        text: 'Verify the firewall rule is active',
        hint: 'iptables -L INPUT -n | grep DROP  or  ufw status',
        pattern: /iptables.*-L|ufw\s+status/i,
        explanation: 'Always verify firewall rules after applying them. iptables -L shows the current ruleset. Confirm your DROP rule appears for the attacker IP.',
        visualEffect: 'restore_node:web-server-1',
        completed: false,
      },
    ],
    completionMessage: '🎉 MISSION COMPLETE! You successfully detected and blocked a SSH brute force attack. The attacker has been blocked at the firewall level and fail2ban will prevent future attempts.',
    learningPoints: ['SSH logs are critical for detecting brute force', 'iptables DROP silently discards packets', 'fail2ban automates IP blocking based on log patterns', 'Rate limiting (-m limit) can prevent volumetric attacks'],
  },
  {
    id: 'ddos-mitigation',
    name: 'DDoS Attack Mitigation',
    category: 'Network Defense',
    difficulty: 2,
    xp: 200,
    estimatedTime: '15 min',
    icon: '💥',
    color: '#ff2244',
    briefing: `CRITICAL: Web server infrastructure is under a massive Distributed Denial of Service attack.\n\nTraffic is coming from hundreds of sources, overwhelming our firewall (fw-main) and causing service degradation. Uptime monitoring shows 503 errors spiking.\n\nMission: Analyze the attack, apply rate limiting, identify and block top source IPs, and restore service availability.`,
    attackConfig: { type: 'ddos', targetId: 'fw-main' },
    systemState: { ddos: true },
    objectives: [
      {
        id: 'analyze-traffic',
        text: 'Analyze network connections to identify the flood',
        hint: 'netstat -an | grep SYN_RECV | wc -l  or  ss -s',
        pattern: /netstat.*-an|ss\s+-s|ss\s+-t|netstat.*SYN/i,
        explanation: 'During a SYN flood, you\'ll see hundreds of connections in SYN_RECV state. This is TCP\'s half-open state when the server receives SYN but the client never completes the handshake.',
        visualEffect: 'show_traffic_storm:fw-main',
        completed: false,
      },
      {
        id: 'check-bandwidth',
        text: 'Check kernel logs for connection table overflow',
        hint: 'dmesg | grep conntrack  or  cat /var/log/kern.log | grep "table full"',
        pattern: /dmesg|kern\.log|cat.*kern|journalctl.*kernel|tail.*kern/i,
        explanation: 'nf_conntrack table full errors mean the kernel\'s connection tracking table is exhausted. This causes legitimate connections to be dropped along with malicious ones.',
        visualEffect: 'flash_node:fw-main',
        completed: false,
      },
      {
        id: 'apply-rate-limit',
        text: 'Apply iptables rate limiting to port 80',
        hint: 'iptables -A INPUT -p tcp --dport 80 -m limit --limit 25/minute --limit-burst 100 -j ACCEPT\niptables -A INPUT -p tcp --dport 80 -j DROP',
        pattern: /iptables.*--limit|iptables.*hashlimit/i,
        explanation: 'Rate limiting with -m limit allows burst traffic but caps sustained rates. --limit 25/minute means at most 25 new connections per minute after the burst is exhausted.',
        visualEffect: 'rate_limit_visual:fw-main',
        completed: false,
      },
      {
        id: 'block-top-sources',
        text: 'Block top attacking IP addresses',
        hint: 'netstat -ntu | awk \'{print $5}\' | cut -d: -f1 | sort | uniq -c | sort -rn | head -5\nThen: iptables -A INPUT -s <TOP_IP> -j DROP',
        pattern: /iptables.*-j\s+DROP|ufw.*deny/i,
        explanation: 'Identifying and blocking top source IPs reduces load even during distributed attacks. In real DDoS scenarios, work with your ISP for upstream BGP blackholing.',
        visualEffect: 'firewall_shield:fw-main',
        completed: false,
      },
      {
        id: 'verify-service',
        text: 'Restart nginx and verify service recovery',
        hint: 'systemctl restart nginx && systemctl status nginx',
        pattern: /systemctl.*restart.*nginx|systemctl.*start.*nginx/i,
        explanation: 'After mitigating the attack, restart the affected service to clear any stuck connections and restore normal operation.',
        visualEffect: 'restore_node:fw-main',
        completed: false,
      },
    ],
    completionMessage: '✅ DDoS MITIGATED! Rate limiting is active and top attackers blocked. Service has been restored. Consider implementing Cloudflare or AWS Shield for persistent DDoS protection.',
    learningPoints: ['SYN floods exhaust the connection tracking table', 'iptables rate limiting reduces volumetric impact', 'BGP blackholing is used for large-scale DDoS at ISP level', 'Anycast diffusion spreads attack traffic across multiple PoPs'],
  },
  {
    id: 'malware-hunt',
    name: 'Malware Investigation',
    category: 'Threat Hunting',
    difficulty: 2,
    xp: 250,
    estimatedTime: '20 min',
    icon: '🦠',
    color: '#ff0055',
    briefing: `THREAT ALERT: EDR system detected anomalous process behavior on web-server-1. A process is consuming 95% CPU and making suspicious outbound connections.\n\nIndicators suggest a Remote Access Trojan (RAT) or cryptominer. The malware may have established persistence via cron or systemd.\n\nMission: Hunt down the malware, kill all malicious processes, remove persistence mechanisms, and contain the threat.`,
    attackConfig: { type: 'malware', targetId: 'workstation-1' },
    systemState: { malware: true },
    objectives: [
      {
        id: 'find-process',
        text: 'Find the suspicious process consuming high CPU',
        hint: 'ps aux | sort -rk 3,3 | head -10  or  top',
        pattern: /ps\s+aux|top\b/i,
        explanation: 'ps aux lists all processes. The %CPU column (3rd) reveals the malicious process "svchost32" consuming 95% CPU. Note: svchost32 is NOT a legitimate Linux process — it\'s masquerading as a Windows process name.',
        visualEffect: 'highlight_node:workstation-1',
        completed: false,
      },
      {
        id: 'check-connections',
        text: 'Check network connections for C2 communication',
        hint: 'ss -tuln  or  netstat -an | grep ESTABLISHED',
        pattern: /ss\s+-tun?l?p?|netstat.*-an|lsof.*-i/i,
        explanation: 'C2 (Command & Control) connections typically use common ports (80, 443, 4444) to blend in. The malware is connecting to 198.51.100.10:4444 — a known C2 server IP.',
        visualEffect: 'show_c2_connection',
        completed: false,
      },
      {
        id: 'kill-malware',
        text: 'Kill the malicious process (PID 4829)',
        hint: 'kill -9 4829  or  killall svchost32',
        pattern: /kill\s+-9\s+4829|kill.*4829|killall.*svchost/i,
        explanation: 'kill -9 sends SIGKILL which cannot be caught or ignored. Use it for processes that refuse to terminate with SIGTERM (kill without -9). Always document PIDs before killing for forensic purposes.',
        visualEffect: 'stop_malware_spread',
        completed: false,
      },
      {
        id: 'check-persistence',
        text: 'Check for persistence mechanisms in crontab',
        hint: 'crontab -l  and  cat /etc/crontab',
        pattern: /crontab\s+-l|cat.*crontab/i,
        explanation: 'Malware commonly installs persistence via crontab (@reboot entries), systemd services, or ~/.bashrc. Always check all persistence locations during incident response.',
        visualEffect: 'highlight_persistence',
        completed: false,
      },
      {
        id: 'remove-malware',
        text: 'Remove malware files from /tmp/.hidden/',
        hint: 'find /tmp -name "*.sh" -o -name "*.py"  then  rm -rf /tmp/.hidden/',
        pattern: /find.*tmp|rm.*tmp.*hidden|rm.*svchost|rm.*beacon/i,
        explanation: 'Attackers often drop files in /tmp because it\'s writable by all users and often excluded from AV scans. Always search /tmp, /dev/shm, and world-writable directories during incident response.',
        visualEffect: 'restore_node:workstation-1',
        completed: false,
      },
    ],
    completionMessage: '🦠 MALWARE CONTAINED! Process killed, C2 communication severed, persistence removed. Recommend: Re-image the system, rotate all credentials, and scan lateral movement targets.',
    learningPoints: ['ps aux reveals abnormal CPU/memory usage', 'C2 beacons use common ports to bypass firewalls', 'Malware persists via cron, systemd, .bashrc, rc.local', '/tmp and /dev/shm are common malware staging areas'],
  },
  {
    id: 'network-forensics',
    name: 'Network Forensics (MITM)',
    category: 'Forensics',
    difficulty: 3,
    xp: 300,
    estimatedTime: '25 min',
    icon: '👁',
    color: '#aa00ff',
    briefing: `SUSPICIOUS ACTIVITY: Network monitoring detected unusual ARP traffic patterns on VLAN 10. Multiple workstations report intermittent connectivity issues and SSL certificate warnings.\n\nEvidence suggests an ARP cache poisoning attack enabling a Man-in-the-Middle interception of internal traffic.\n\nMission: Confirm the MITM, identify the attacker, capture evidence, and remediate.`,
    attackConfig: { type: 'mitm', targetId: 'router-core' },
    systemState: { mitm: true },
    objectives: [
      {
        id: 'detect-arp',
        text: 'Inspect ARP table for duplicate/spoofed entries',
        hint: 'arp -n  or  ip neigh show',
        pattern: /arp\s+-n|arp\s+-a|ip\s+neigh/i,
        explanation: 'ARP (Address Resolution Protocol) maps IP to MAC addresses. In ARP spoofing, the attacker sends fake ARP replies, poisoning the victim\'s cache so traffic goes to the attacker instead of the legitimate gateway.',
        visualEffect: 'highlight_mitm',
        completed: false,
      },
      {
        id: 'capture-traffic',
        text: 'Capture suspicious ARP traffic with tcpdump',
        hint: 'tcpdump -i eth0 arp  or  tcpdump -i eth0 -n',
        pattern: /tcpdump.*arp|tcpdump.*-i/i,
        explanation: 'tcpdump captures raw network packets. Filtering for ARP traffic reveals who is sending gratuitous ARP replies. The attacker\'s IP and MAC address will appear in the captures.',
        visualEffect: 'show_packet_capture',
        completed: false,
      },
      {
        id: 'identify-attacker',
        text: 'Identify attacker IP from duplicate MAC',
        hint: 'Look for the MAC address de:ad:be:ef:00:01 in your ARP output',
        pattern: /grep.*de:ad|grep.*attacker|arp.*n|ip.*neigh/i,
        explanation: 'The attacker MAC de:ad:be:ef:00:01 is appearing for the gateway IP 192.168.1.1. The real gateway has MAC 00:50:56:c0:00:01. Tracing the spoofed MAC to a physical port identifies the attacker\'s machine.',
        visualEffect: 'identify_attacker',
        completed: false,
      },
      {
        id: 'block-attacker',
        text: 'Block the attacker IP at the firewall',
        hint: 'iptables -A INPUT -s 192.168.1.99 -j DROP (or the identified attacker IP)',
        pattern: /iptables.*DROP|ufw.*deny/i,
        explanation: 'Blocking at L3 (IP layer) stops the attack immediately. For a more complete fix, implement Dynamic ARP Inspection (DAI) on managed switches and deploy 802.1X port authentication.',
        visualEffect: 'stop_mitm',
        completed: false,
      },
      {
        id: 'restore-arp',
        text: 'Flush ARP cache to restore correct mappings',
        hint: 'ip -s -s neigh flush all  or  arp -d 192.168.1.1',
        pattern: /ip.*neigh.*flush|arp\s+-d/i,
        explanation: 'Flushing the ARP cache forces all hosts to re-request correct MAC addresses. Combined with blocking the attacker, this restores normal traffic flow.',
        visualEffect: 'restore_node:router-core',
        completed: false,
      },
    ],
    completionMessage: '🔍 MITM DETECTED AND CONTAINED! ARP spoofing eliminated. Recommend: Enable Dynamic ARP Inspection on all switches, implement 802.1X, and consider encrypted tunnels (VPN) for sensitive communications.',
    learningPoints: ['ARP has no authentication — anyone can send fake replies', 'Dynamic ARP Inspection (DAI) validates ARP packets on switches', '802.1X provides port-level network access control', 'HTTPS/TLS protects against MITM even if ARP is poisoned'],
  },
  {
    id: 'ransomware-ir',
    name: 'Ransomware Incident Response',
    category: 'Incident Response',
    difficulty: 3,
    xp: 350,
    estimatedTime: '30 min',
    icon: '🔒',
    color: '#ff0000',
    briefing: `🚨 CRITICAL INCIDENT: Ransomware has been detected on workstation-1 and is actively spreading through network shares.\n\nFile encryption is in progress. Shadow copies are being deleted. Multiple systems are reporting .locked file extensions. The ransom note demands 2.5 BTC.\n\nTime-critical: Isolate affected systems IMMEDIATELY to prevent further spread. Then conduct forensic investigation.`,
    attackConfig: { type: 'ransomware', targetId: 'workstation-1' },
    systemState: { malware: true, ransomware: true },
    objectives: [
      {
        id: 'detect-encryption',
        text: 'Identify the ransomware process',
        hint: 'ps aux | grep -E "encrypt|lock|crypt"  or  top (look for unusual high I/O)',
        pattern: /ps\s+aux|top\b|lsof/i,
        explanation: 'Ransomware typically shows as a process with high disk I/O rather than CPU. Tools like iotop or lsof -p <PID> can show which files are being opened and written — look for .locked or unusual extensions.',
        visualEffect: 'ransomware_spread_visual',
        completed: false,
      },
      {
        id: 'stop-spread',
        text: 'Block all SMB traffic to prevent lateral spread',
        hint: 'iptables -A INPUT -p tcp --dport 445 -j DROP\niptables -A OUTPUT -p tcp --dport 445 -j DROP',
        pattern: /iptables.*445|ufw.*deny.*445|iptables.*smb/i,
        explanation: 'Ransomware spreads through SMB (port 445) file shares. Blocking this port network-wide prevents the ransomware from encrypting mapped drives on other machines.',
        visualEffect: 'block_smb_spread',
        completed: false,
      },
      {
        id: 'kill-process',
        text: 'Kill all ransomware processes',
        hint: 'kill -9 4829  and  killall svchost32',
        pattern: /kill.*-9|killall/i,
        explanation: 'Killing the process stops ongoing encryption but won\'t decrypt already-encrypted files. Speed is critical — every second the process runs, more files are encrypted.',
        visualEffect: 'stop_encryption',
        completed: false,
      },
      {
        id: 'check-shadows',
        text: 'Check if shadow copies were deleted',
        hint: 'ls /var/lib/lvm/ or check vssadmin in Windows environments',
        pattern: /ls.*lvm|find.*shadow|lvs\b|vgdisplay/i,
        explanation: 'Modern ransomware deletes VSS (Volume Shadow Service) copies to prevent recovery. In Linux environments, check LVM snapshots. Always maintain offline backups that cannot be reached by ransomware.',
        visualEffect: 'check_backup_status',
        completed: false,
      },
      {
        id: 'isolate-network',
        text: 'Fully isolate the infected host',
        hint: 'iptables -A INPUT -j DROP && iptables -A OUTPUT -j DROP (on infected host)',
        pattern: /iptables.*-A\s+INPUT.*DROP|iptables.*-A\s+OUTPUT.*DROP|iptables.*-P.*DROP/i,
        explanation: 'After stopping active spread, fully isolate the host for forensic analysis. This prevents any remaining malware from beaconing out or receiving new instructions.',
        visualEffect: 'isolate_node:workstation-1',
        completed: false,
      },
    ],
    completionMessage: '🔒 RANSOMWARE CONTAINED! Spread stopped via SMB block, process killed, host isolated. Recovery options: restore from backup. Lessons: Offline backups, network segmentation, email filtering.',
    learningPoints: ['Ransomware spreads via SMB (port 445) and RDP (port 3389)', 'Shadow copies (VSS) provide quick recovery if not deleted', 'Offline/immutable backups are the only true protection', 'Network segmentation limits blast radius of ransomware'],
  },
  {
    id: 'phishing-response',
    name: 'Phishing Email Investigation',
    category: 'Social Engineering',
    difficulty: 2,
    xp: 180,
    estimatedTime: '15 min',
    icon: '🎣',
    color: '#ffff00',
    briefing: `USER REPORT: Multiple employees received suspicious emails purporting to be from IT Security. The emails contain links to a credential harvesting page at http://l0gin-corp[.]com.\n\nThree employees may have clicked the link and entered credentials. The phishing site mimics our corporate login portal.\n\nMission: Investigate email logs, block the phishing domain, identify compromised accounts, and force password resets.`,
    attackConfig: { type: 'phishing', targetId: 'workstation-2' },
    systemState: { phishing: true },
    objectives: [
      {
        id: 'check-mail-logs',
        text: 'Check mail server logs for phishing emails',
        hint: 'cat /var/log/mail.log | grep -i "l0gin-corp"  or  journalctl -u postfix',
        pattern: /cat.*mail\.log|journalctl.*postfix|grep.*mail|grep.*phish/i,
        explanation: 'Mail server logs record all received and sent messages with envelope headers. The From: address is spoofed but the Received headers reveal the true originating IP.',
        visualEffect: 'highlight_node:mail-server',
        completed: false,
      },
      {
        id: 'analyze-headers',
        text: 'Analyze email headers to identify sender IP',
        hint: 'grep "Received: from" /var/log/mail.log | tail -20',
        pattern: /grep.*Received|grep.*From:|grep.*mail/i,
        explanation: 'Email headers contain the full routing path. The topmost "Received:" header shows the last server that handled the email — working backwards reveals the true origin despite spoofed From: addresses.',
        visualEffect: 'show_email_path',
        completed: false,
      },
      {
        id: 'block-domain',
        text: 'Block the phishing domain at the firewall',
        hint: 'iptables -A OUTPUT -d l0gin-corp.com -j DROP  or add to /etc/hosts: 0.0.0.0 l0gin-corp.com',
        pattern: /iptables.*l0gin|iptables.*DROP.*OUTPUT|echo.*0\.0\.0\.0.*hosts|ufw.*deny/i,
        explanation: 'Blocking at the firewall prevents any further connections to the phishing site. DNS-level blocking (Pi-hole, RPZ) is more effective as it covers all protocols, not just HTTP/HTTPS.',
        visualEffect: 'block_phishing_portal',
        completed: false,
      },
      {
        id: 'check-compromised',
        text: 'Check for unauthorized logins from new locations',
        hint: 'grep "Accepted password" /var/log/auth.log | grep -v "10.0.0."',
        pattern: /grep.*Accepted.*auth|grep.*login.*auth|cat.*auth\.log/i,
        explanation: 'After credential theft, attackers log in from unusual IPs or geolocations. "Accepted password" from non-internal IPs is a strong indicator of compromised credentials.',
        visualEffect: 'highlight_compromised_accounts',
        completed: false,
      },
      {
        id: 'force-resets',
        text: 'Force password reset for affected users',
        hint: 'passwd -e username  (forces password change on next login)',
        pattern: /passwd\s+-e|usermod.*-e|chage.*-d/i,
        explanation: 'passwd -e expires the password immediately. Combined with session invalidation and MFA enforcement, this mitigates the impact of stolen credentials.',
        visualEffect: 'restore_node:workstation-2',
        completed: false,
      },
    ],
    completionMessage: '🎣 PHISHING CAMPAIGN NEUTRALIZED! Domain blocked, credentials rotated. Recommendations: Deploy DMARC/DKIM/SPF, enable email sandboxing, conduct security awareness training.',
    learningPoints: ['DMARC/DKIM/SPF prevent email spoofing at DNS level', 'Email headers trace the true origin despite spoofed From:', 'MFA is the most effective defense against credential theft', 'DNS-level blocking (RPZ, Pi-hole) covers all protocols'],
  },
];

export const DIFFICULTY_LABELS = { 1: 'Beginner', 2: 'Intermediate', 3: 'Advanced' };
export const DIFFICULTY_COLORS = { 1: '#00ff88', 2: '#ffcc00', 3: '#ff2244' };
